#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - Discounted value of a series of cash flows.

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} [OPTIONS] < datafile
  cat datafile | ${me} [OPTIONS] 

DESCRIPTION
  ${me} computes the discounted value of a stream of cash flow pairs
  (t,R) where the amount R of each pair is discounted for t time periods
  compounded.

OPTIONS
  -h  Displays help message.

  -i i
    Interest rate per period. Defaults to 0.

  -k k
    Number of decimal digits precision to retain in calculations.
    Defaults to 4.

AUTHOR
  Berend M. Tober

"

i=0
k=4
infile="-"

while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h)
      echo "${usage}"
      exit
      ;;
    -i)
      i="${2}"
      shift 2
      ;;
    -k)
      k="${2}"
      shift 2
      ;;
    -*)
      echo "Invalid option '${1}'"
      exit
      ;;
  esac

  infile="${1--}"
  shift
done  

cat "${infile}" | awk -v i="$i" '
  {print $1, $2/(1+i)^$1};
'
