#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - Sort and counts input data set, producing a listing
  of unique input items and their frequency count.

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} < datafile
  cat datafile | ${me} 

DESCRIPTION
  ${me} Reads the input data and then outputs a frequency
  count of the unique values.

  For example, a datafile may appear as follows:

    b
    b
    a
    d
    a
    c
    d

OPTIONS
  -h  Displays help message.

AUTHOR
  Berend M. Tober

"

case "${1}" in
  -h)
    echo "${usage}"
    exit
    ;;
  -*)
    echo "Invalid option '${1}'"
    exit
    ;;
esac

cat "${@}" | sort | uniq -c | sort -n -r
