#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - Convert Unix time stamp (seconds since epoch) to 
  date/time formatted as YYYY-MM-DD HH:MM:SS.

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} < datafile
  cat datafile | ${me} 

DESCRIPTION
  ${me} Reads the input data and then outputs a date/time. 

OPTIONS
  -h  Displays help message.
  -t  Suppress time output.
  -d  Suppress date output.

AUTHOR
  Berend M. Tober

"

unset notime nodate formatstr

infile="-"

while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h)
      echo "${usage}"
      exit
      ;;
    -t)
      notime=1
      shift
      ;;
    -d)
      nodate=1
      shift
      ;;
    -*)
      echo "Invalid option '${1}'"
      exit
      ;;
  esac
  infile="${1--}"
  shift
done  

[[ -z "${nodate}" ]] && formatstr="${formatstr}%F"
[[ -z "${notime}" ]] && formatstr="${formatstr} %T"

formatstr="${formatstr#[[:space:]]}"

cat "${infile}" | while read n
do
  date -d "@${n}" "+${formatstr}"
done  
