#!/bin/bash

me=$(basename $0)

usage="
NAME
  ${me} - Computes magnitude of a vector.

SYNOPSIS
  ${me} vector

DESCRIPTION
  ${me} computes the magnitude of a vector.  The input vector
  file must be lines of ordered pairs, sorted by the second
  element, and where the first element of each pair is the
  magnitude, and the second element of each pair is the
  dimension name.  This allows for arbitrary vector spaces
  with points specified sparsely.

  For example, a vector file may appear as follows:

    3 x
    4 y
    5 z

  for a vector with components x=3, y=4, and z=5.
 
"

if [[ ${#} -lt 1 ]]
then
  echo "${usage}"
  exit
fi

bc -l <<< "sqrt($(vdot ${1} ${1}))"


